import antfu from "@antfu/eslint-config"

// ESLint is also the formatter (antfu's stylistic rules); there is no Prettier.
export default antfu(
  {
    react: true,
    // No pnpm catalog / workspace-settings rules: this is a single package.
    pnpm: false,
    typescript: true,
    stylistic: {
      indent: 2,
      quotes: "double",
      semi: false,
    },
    ignores: [
      // Stock shadcn/ui, byte-identical to the registry: never touched by tooling.
      "src/components/ui/**",
      // Generated by unplugin-auto-import.
      "src/auto-imports.d.ts",
      "dist/**",
      ".playwright-mcp/**",
    ],
  },
)
